# -*- coding: utf-8 -*-
"""Jira_cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygNEdgf0cjfCoAkrnk6kCAyU0eMsxyO7
"""

import pandas as pd
import re
import spacy
import numpy as np
nlp = spacy.load("en_core_web_sm")
import ssl
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import silhouette_score

# Make sure to have NLTK's stopwords downloaded
import nltk
nltk.download('punkt')
nltk.download('stopwords')

data = pd.read_csv('')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('final_jira.csv')
def plot_counts_and_percentage(dataframe, column_name):
    counts = dataframe[column_name].value_counts()
    percentage = (dataframe[column_name].value_counts(normalize=True) * 100).round(2)
    plot_data = pd.DataFrame({column_name: counts.index, 'Counts': counts.values, 'Percentage': percentage.values})
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    sns.barplot(x='Counts', y=column_name, data=plot_data, ax=axes[0])
    axes[0].set_title(f'Count Plot for {column_name}')
    sns.barplot(x='Percentage', y=column_name, data=plot_data, ax=axes[1])
    axes[1].set_title(f'Percentage Plot for {column_name}')
    plt.tight_layout()
    plt.show()

plot_counts_and_percentage(data, 'Os')
plot_counts_and_percentage(data, 'Priority')
plot_counts_and_percentage(data, 'Status')

data['Summary']
import re
from bs4 import BeautifulSoup
import string
import re

def clean_text(text):
    text = str(text)
    soup = BeautifulSoup(text, "html.parser")
    cleaned_text = soup.get_text()
    cleaned_text = re.sub(r'\n', ' ', cleaned_text)  # Replace newline characters with space
    cleaned_text = re.sub(r'[{}]', '', cleaned_text)  # Remove curly braces
    # cleaned_text = clean(cleaned_text,
    #                      fix_unicode=True,  # fix various unicode errors
    #                      to_ascii=True,  # transliterate to closest ASCII representation
    #                      lower=False,  # lowercase text
    #                      no_line_breaks=True,  # remove line breaks
    #                      no_urls=True,  # replace all URLs with special token
    #                      no_emails=True,  # replace all email addresses with special token
    #                      no_phone_numbers=True,  # replace all phone numbers with special token
    #                      no_currency_symbols=True,  # replace all currency symbols with special token
    #                      no_punct=True,  # remove punctuations
    #                      replace_with_url="",  # replace each URL with this token
    #                      replace_with_email="",  # replace each email with this token
    #                      replace_with_phone_number="",  # replace each phone number with this token
    #                      replace_with_currency_symbol="",  # replace each currency symbol with this token
    #                      replace_with_punct="",  # replace each punctuation symbol with this token
    #                      lang="en"  # set to 'en' for English
    #                      )
    return cleaned_text
data['Description'] = data['Description'].apply(clean_text)
data['Summary'] = data['Summary'].apply(clean_text)
data['COMMENTS'] = data['COMMENTS'].apply(clean_text)

from sklearn.feature_extraction.text import CountVectorizer
data['Description'].fillna('', inplace=True)
data['Summary'].fillna('', inplace=True)

all_text = np.concatenate((data['Description'], data['Summary']))

count_vect = CountVectorizer()
word_count_matrix = count_vect.fit_transform(all_text)
total_unique_words = len(count_vect.get_feature_names_out())
print(f"Total unique words for Description and Summary: {total_unique_words}")

count_vect = CountVectorizer()
word_count_matrix_desc = count_vect.fit_transform(data['Description'])
total_unique_words_desc = len(count_vect.get_feature_names_out())

count_vect = CountVectorizer()
word_count_matrix_summ = count_vect.fit_transform(data['Summary'])
total_unique_words_summ = len(count_vect.get_feature_names_out())

print(f"Total unique words in 'Description': {total_unique_words_desc}")
print(f"Total unique words in 'Summary': {total_unique_words_summ}")



"""**TF-IDF**"""

# max_features: 200, 500, 1000, 2000, 5000

# For description
tfidf_vectorizer = TfidfVectorizer(max_features=200)
tfidf_matrix = tfidf_vectorizer.fit_transform(data['Description'])
tfidf_dense = tfidf_matrix.todense()
tfidf_dense_array = np.asarray(tfidf_dense)

"""**K-Means**"""

# For Description
pca1 = PCA(n_components=2)
principalComponents = pca1.fit_transform(tfidf_dense_array)

# For Description
num_clusters = 5
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
clusters = kmeans.fit_predict(tfidf_matrix)

plt.figure(figsize=(7,5))
plt.scatter(principalComponents[:,0],principalComponents[:,1],c=clusters,cmap='viridis')
plt.title('K-Means Clustering for Description (TFIDF)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.show()

#kmeans silhouette score
score_SH1 = silhouette_score(tfidf_matrix,clusters)

print(f'Silhouette Score for TFIDF Description :{score_SH1}')

num_clusters_list = range(1, 11)
inertias = []
for k in num_clusters_list:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(tfidf_matrix)
    inertias.append(kmeans.inertia_)

plt.figure(figsize=(7,5))
plt.plot(num_clusters_list, inertias, '-o')
plt.title('Elbow Method For Optimal k (TFIDF, Description)')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.xticks(num_clusters_list)
plt.show()

# For summary
tfidf_vectorizer2 = TfidfVectorizer(max_features=100)
tfidf_matrix2 = tfidf_vectorizer2.fit_transform(data['Summary'])

tfidf_dense2 = tfidf_matrix2.todense()
tfidf_dense_array2 = np.asarray(tfidf_dense2)

# For Summary
pca2 = PCA(n_components=2)
principalComponents2 = pca2.fit_transform(tfidf_dense_array2)

num_clusters_list = range(1, 11)
inertias = []
for k in num_clusters_list:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(tfidf_matrix2)
    inertias.append(kmeans.inertia_)

plt.figure(figsize=(7,5))
plt.plot(num_clusters_list, inertias, '-o')
plt.title('Elbow Method For Optimal k (TFIDF, Description)')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.xticks(num_clusters_list)
plt.show()

# For Summary
num_clusters2 = 6
kmeans2 = KMeans(n_clusters=num_clusters2, random_state=42)
clusters2 = kmeans2.fit_predict(tfidf_matrix2)

plt.figure(figsize=(7,5))
plt.scatter(principalComponents2[:,0],principalComponents2[:,1],c=clusters2,cmap='viridis')
plt.title('K-Means Clustering for Summary (TFIDF)')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.show()

#kmeans silhouette score for summary
score_SH2 = silhouette_score(tfidf_matrix2,clusters2)

print(f'Silhouette Score for TFIDF Summary:{score_SH2}')

"""**Hierarchial Clustering**"""

# Description
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_dist = 1 - cosine_sim
Z = linkage(cosine_dist, method='average')

from sklearn.metrics import calinski_harabasz_score
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster


scores = []
n_clusters_list = range(2, 11)

for n_clusters in n_clusters_list:
    clusters = fcluster(Z, n_clusters, criterion='maxclust')
    score = calinski_harabasz_score(cosine_dist, clusters)
    scores.append(score)

plt.figure(figsize=(6, 3))
plt.plot(n_clusters_list, scores, marker='o')
plt.xlabel('Number of Clusters')
plt.ylabel('Calinski-Harabasz Score')
plt.title('Calinski-Harabasz Scores for Different Numbers of Clusters')
plt.show()

plt.figure(figsize=(7, 5))
dendrogram(Z)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("")  # This will clear any text if it was set previously
plt.ylabel("Distance")
plt.xticks([])  # This removes the x-axis tick marks and labels
plt.show()

from scipy.cluster.hierarchy import fcluster
distance_threshold = 5.5
clusters_hc = fcluster(Z, distance_threshold, criterion='distance')

plt.figure(figsize=(7,5))
plt.scatter(principalComponents[:, 0], principalComponents[:, 1], c=clusters_hc,  marker='o', alpha=0.7)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title("Hierarchical Clustering Visualization (TFIDF)")
plt.show()

from scipy.cluster.hierarchy import linkage, fcluster
from sklearn.metrics.pairwise import cosine_similarity


num_clusters = range(2, 10)

SH_scores = []
for k in num_clusters:
    clusters_hc = fcluster(Z, k, criterion='maxclust')
    score = silhouette_score(tfidf_matrix,clusters_hc)
    SH_scores.append(score)

plt.figure(figsize=(7,5))
plt.plot(num_clusters, SH_scores, marker='o')
plt.title('Silhouette Score over Numbers of Clusters')
plt.xlabel('Number of Clusters')
plt.ylabel('Silhouette Score')
plt.xticks(num_clusters)
plt.show()

clusters_hc_final= fcluster(Z, 4, criterion='maxclust')
score_SH_hc1 = silhouette_score(tfidf_matrix,clusters_hc_final)
print(f'Silhouette Score for TFIDF Description HC: {score_SH_hc1}')

plt.figure(figsize=(7, 5))
plt.scatter(principalComponents[:, 0], principalComponents[:, 1], c=clusters_hc_final,  marker='o', alpha=0.7)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title("Hierarchical Clustering Visualization (TFIDF)")
plt.show()

"""**HC for Summary**"""

cosine_sim2 = cosine_similarity(tfidf_matrix2)
cosine_dist2 = 1 - cosine_sim2
Z2 = linkage(cosine_dist2, method='average')

plt.figure(figsize=(7, 5))
dendrogram(Z2)
plt.title("Hierarchial Clustering Dendrogram")
plt.xlabel("Index")
plt.ylabel("Distance")
plt.show()

distance_threshold2 = 5.5
clusters_hc2 = fcluster(Z2, distance_threshold2, criterion='distance')


plt.figure(figsize=(7,5))
plt.scatter(principalComponents2[:, 0], principalComponents2[:, 1], c=clusters_hc2,  marker='o', alpha=0.7)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title("Hierarchical Clustering Visualization (TFIDF)")
plt.show()

num_clusters = range(2, 12)

SH_scores2 = []
for k in num_clusters:
    clusters_hc_tem = fcluster(Z2, k, criterion='maxclust')
    score = silhouette_score(tfidf_matrix2,clusters_hc_tem)
    SH_scores2.append(score)

plt.figure(figsize=(7,5))
plt.plot(num_clusters, SH_scores2, marker='o')
plt.title('Silhouette Score over Numbers of Clusters')
plt.xlabel('Number of Clusters')
plt.ylabel('Silhouette Score')
plt.xticks(num_clusters)
plt.show()

clusters_hc_final2= fcluster(Z2, 9, criterion='maxclust')
score_SH_hc2 = silhouette_score(tfidf_matrix2,clusters_hc_final2)
print(f'Silhouette Score for TFIDF Summary HC: {score_SH_hc2}')

plt.figure(figsize=(7, 5))
plt.scatter(principalComponents2[:, 0], principalComponents2[:, 1], c=clusters_hc_final2,  marker='o', alpha=0.7)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title("Hierarchical Clustering Visualization (TFIDF)")
plt.show()

"""**Consider Summary and Frequent devices**"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
vectorizer = CountVectorizer(ngram_range=(2, 2), stop_words='english')

bigrams_matrix = vectorizer.fit_transform(data['Summary'])

bigrams = vectorizer.get_feature_names_out()

bigram_frequencies = bigrams_matrix.sum(axis=0)
bigram_frequencies = np.array(bigram_frequencies).flatten()
bigrams_with_frequencies = list(zip(bigrams, bigram_frequencies))

most_frequent_bigrams = sorted(bigrams_with_frequencies, key=lambda x: x[1], reverse=True)

for bigram, freq in most_frequent_bigrams[:100]:
    print(f"{bigram}: {freq}")

data_copy = data.copy()
import re

replacements = {
    r'\bg6 io\b': 'g6 ios',
    r'\bg7 io\b': 'g7 ios',
}

for old, new in replacements.items():
    data_copy['Summary'] = data_copy['Summary'].replace(old, new, regex=True)

vectorizer = CountVectorizer(ngram_range=(2, 2), stop_words='english')

bigrams_matrix = vectorizer.fit_transform(data_copy['Summary'])

bigrams = vectorizer.get_feature_names_out()

bigram_frequencies = bigrams_matrix.sum(axis=0)
bigram_frequencies = np.array(bigram_frequencies).flatten()
bigrams_with_frequencies = list(zip(bigrams, bigram_frequencies))

most_frequent_bigrams = sorted(bigrams_with_frequencies, key=lambda x: x[1], reverse=True)

for bigram, freq in most_frequent_bigrams[:15]:
    print(f"{bigram}: {freq}")

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

vectorizer = CountVectorizer(ngram_range=(1, 1), stop_words=['english'], min_df=2)
bigrams_matrix = vectorizer.fit_transform(data['Summary'])
bigram_frequencies = bigrams_matrix.sum(axis=0)
bigram_frequencies = np.array(bigram_frequencies).flatten()

bigrams_with_frequencies = list(zip(vectorizer.get_feature_names_out(), bigram_frequencies))
most_frequent_bigrams = sorted(bigrams_with_frequencies, key=lambda x: x[1], reverse=True)[:10]

top_bigrams = [bigram[0] for bigram in most_frequent_bigrams]

data['Unigram_Group'] = 'Other'

for bigram in top_bigrams:
    mask = data['Summary'].str.contains(bigram.replace(' ', '\s+'), regex=True, case=False)
    data.loc[mask & (data['Unigram_Group'] == 'Other'), 'Unigram_Group'] = bigram

print(data['Unigram_Group'].value_counts())

for name, group in data.groupby('Unigram_Group'):
    print(f"Group: {name}")
    print(group['Summary'].head(5))
    print("\n")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

columns = ['Status', 'Resolution', 'Os', 'Issue_Type', 'Priority']


for col in columns:
    plt.figure(figsize=(6, 4))
    sns.countplot(y=col, data=data, order = data[col].value_counts().index)
    plt.title(f'Distribution of {col}')
    plt.xlabel('Count')
    plt.ylabel(col)
    plt.show()

from scipy.spatial.distance import euclidean
import numpy as np


def min_I(X, labels, cluster_i, cluster_j):
    points_i=X[labels == cluster_i]
    points_j=X[labels == cluster_j]
    min_dist=np.inf
    for point_i in points_i:
        for point_j in points_j:
            dist=euclidean(point_i, point_j)
            if dist < min_dist:
                min_dist=dist
    return min_dist


def max_I(X, labels, cluster_i):
    points_i=X[labels==cluster_i]
    max_dist=0
    for point_i in points_i:
        for point_j in points_i:
            dist=euclidean(point_i, point_j)
            if dist > max_dist:
                max_dist=dist
    return max_dist
def dunn_index(X, labels):
    unique_labels=np.unique(labels)
    min_inter=np.inf
    max_intra=0
    for i in range(len(unique_labels)):
        for j in range(i + 1, len(unique_labels)):
            inter_dist=min_I(X, labels, unique_labels[i], unique_labels[j])
            if inter_dist < min_inter:
                min_inter=inter_dist
    for i in unique_labels:
        intra_dist=max_I(X, labels, i)
        if intra_dist > max_intra:
            max_intra=intra_dist
    return min_inter/max_intra

dunn_index(tfidf_matrix,clusters_hc_final)

dunn_index(tfidf_matrix,clusters)